apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: kibana-plugins
  name: kibana-plugins
  namespace: kubeprod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
