apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  labels:
    name: letsencrypt-prod-dns
  name: letsencrypt-prod-dns
spec:
  acme:
    dns01:
      providers:
      - name: letsencrypt-prod-dns
        route53:
          region: us-east-1
    email: itamar@cosmic.rocks
    privateKeySecretRef:
      name: letsencrypt-prod-dns
    server: https://acme-v02.api.letsencrypt.org/directory
